// Mocks generated by Mockito 5.3.2 from annotations
// in search/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core/utils/failure.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie/domain/entities/movie.dart' as _i6;
import 'package:movie/domain/entities/movie_detail.dart' as _i7;
import 'package:movie/domain/repositories/movie_repository.dart' as _i3;
import 'package:tv_series/domain/entities/tv_series.dart' as _i9;
import 'package:tv_series/domain/entities/tv_series_detail.dart' as _i10;
import 'package:tv_series/domain/entities/tv_series_season_detail.dart' as _i11;
import 'package:tv_series/domain/repositories/tv_series_repository.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i3.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> getNowPlayingMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingMovies,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Movie>>(
          this,
          Invocation.method(
            #getNowPlayingMovies,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Movie>>(
          this,
          Invocation.method(
            #getPopularMovies,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Movie>>(
          this,
          Invocation.method(
            #getTopRatedMovies,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.MovieDetail>>.value(
            _FakeEither_0<_i5.Failure, _i7.MovieDetail>(
          this,
          Invocation.method(
            #getMovieDetail,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.MovieDetail>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> getMovieRecommendations(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieRecommendations,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Movie>>(
          this,
          Invocation.method(
            #getMovieRecommendations,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> searchMovies(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Movie>>(
          this,
          Invocation.method(
            #searchMovies,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);
}

/// A class which mocks [TVSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesRepository extends _i1.Mock
    implements _i8.TVSeriesRepository {
  MockTVSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.TVSeries>>>
      getOnTheAirTVSeries() => (super.noSuchMethod(
            Invocation.method(
              #getOnTheAirTVSeries,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i9.TVSeries>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i9.TVSeries>>(
              this,
              Invocation.method(
                #getOnTheAirTVSeries,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i9.TVSeries>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.TVSeries>>>
      getPopularTVSeries() => (super.noSuchMethod(
            Invocation.method(
              #getPopularTVSeries,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i9.TVSeries>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i9.TVSeries>>(
              this,
              Invocation.method(
                #getPopularTVSeries,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i9.TVSeries>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.TVSeries>>>
      getTopRatedTVSeries() => (super.noSuchMethod(
            Invocation.method(
              #getTopRatedTVSeries,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i9.TVSeries>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i9.TVSeries>>(
              this,
              Invocation.method(
                #getTopRatedTVSeries,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i9.TVSeries>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.TVSeriesDetail>> getDetailTVSeries(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailTVSeries,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i10.TVSeriesDetail>>.value(
                _FakeEither_0<_i5.Failure, _i10.TVSeriesDetail>(
          this,
          Invocation.method(
            #getDetailTVSeries,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i10.TVSeriesDetail>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.TVSeries>>>
      getRecommendationTVSeries(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getRecommendationTVSeries,
              [id],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i9.TVSeries>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i9.TVSeries>>(
              this,
              Invocation.method(
                #getRecommendationTVSeries,
                [id],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i9.TVSeries>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i11.TVSeriesSeasonDetail>>
      getSeasonDetailTVSeries(
    int? id,
    int? season,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getSeasonDetailTVSeries,
              [
                id,
                season,
              ],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i11.TVSeriesSeasonDetail>>.value(
                _FakeEither_0<_i5.Failure, _i11.TVSeriesSeasonDetail>(
              this,
              Invocation.method(
                #getSeasonDetailTVSeries,
                [
                  id,
                  season,
                ],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i11.TVSeriesSeasonDetail>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.TVSeries>>> searchTVSeries(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTVSeries,
          [query],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i9.TVSeries>>>.value(
                _FakeEither_0<_i5.Failure, List<_i9.TVSeries>>(
          this,
          Invocation.method(
            #searchTVSeries,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i9.TVSeries>>>);
}
