// Mocks generated by Mockito 5.3.0 from annotations
// in ditonton/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:convert' as _i24;
import 'dart:typed_data' as _i25;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ditonton/common/failure.dart' as _i9;
import 'package:ditonton/data/datasources/db/database_helper.dart' as _i22;
import 'package:ditonton/data/datasources/movie_remote_data_source.dart'
    as _i12;
import 'package:ditonton/data/datasources/tv_series_remote_data_source.dart'
    as _i20;
import 'package:ditonton/data/datasources/watchlist_local_data_source.dart'
    as _i14;
import 'package:ditonton/data/models/movie/movie_detail_model.dart' as _i3;
import 'package:ditonton/data/models/movie/movie_model.dart' as _i13;
import 'package:ditonton/data/models/tv/tv_series_detail_response_model.dart'
    as _i4;
import 'package:ditonton/data/models/tv/tv_series_model.dart' as _i21;
import 'package:ditonton/data/models/tv/tv_series_season_detail_model.dart'
    as _i5;
import 'package:ditonton/data/models/watchlist_table.dart' as _i15;
import 'package:ditonton/domain/entities/movie/movie.dart' as _i10;
import 'package:ditonton/domain/entities/movie/movie_detail.dart' as _i11;
import 'package:ditonton/domain/entities/tv/tv_series.dart' as _i17;
import 'package:ditonton/domain/entities/tv/tv_series_detail.dart' as _i18;
import 'package:ditonton/domain/entities/tv/tv_series_season_detail.dart'
    as _i19;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i7;
import 'package:ditonton/domain/repositories/tv_series_repository.dart' as _i16;
import 'package:http/http.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i23;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeMovieDetailResponse_1 extends _i1.SmartFake
    implements _i3.MovieDetailResponse {
  _FakeMovieDetailResponse_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTVSeriesDetailResponseModel_2 extends _i1.SmartFake
    implements _i4.TVSeriesDetailResponseModel {
  _FakeTVSeriesDetailResponseModel_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTVSeriesSeasonDetailModel_3 extends _i1.SmartFake
    implements _i5.TVSeriesSeasonDetailModel {
  _FakeTVSeriesSeasonDetailModel_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeResponse_4 extends _i1.SmartFake implements _i6.Response {
  _FakeResponse_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeStreamedResponse_5 extends _i1.SmartFake
    implements _i6.StreamedResponse {
  _FakeStreamedResponse_5(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i7.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> getNowPlayingMovies() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingMovies, []),
              returnValue:
                  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
                      _FakeEither_0<_i9.Failure, List<_i10.Movie>>(
                          this, Invocation.method(#getNowPlayingMovies, []))))
          as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(Invocation.method(#getPopularMovies, []),
              returnValue:
                  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
                      _FakeEither_0<_i9.Failure, List<_i10.Movie>>(
                          this, Invocation.method(#getPopularMovies, []))))
          as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedMovies, []),
              returnValue:
                  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
                      _FakeEither_0<_i9.Failure, List<_i10.Movie>>(
                          this, Invocation.method(#getTopRatedMovies, []))))
          as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, _i11.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
              returnValue:
                  _i8.Future<_i2.Either<_i9.Failure, _i11.MovieDetail>>.value(
                      _FakeEither_0<_i9.Failure, _i11.MovieDetail>(
                          this, Invocation.method(#getMovieDetail, [id]))))
          as _i8.Future<_i2.Either<_i9.Failure, _i11.MovieDetail>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> getMovieRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
              returnValue:
                  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
                      _FakeEither_0<_i9.Failure, List<_i10.Movie>>(this,
                          Invocation.method(#getMovieRecommendations, [id]))))
          as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> searchMovies(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [query]),
              returnValue:
                  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
                      _FakeEither_0<_i9.Failure, List<_i10.Movie>>(
                          this, Invocation.method(#searchMovies, [query]))))
          as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, String>> saveWatchlist(
          _i11.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [movie]),
              returnValue: _i8.Future<_i2.Either<_i9.Failure, String>>.value(
                  _FakeEither_0<_i9.Failure, String>(
                      this, Invocation.method(#saveWatchlist, [movie]))))
          as _i8.Future<_i2.Either<_i9.Failure, String>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, String>> removeWatchlist(
          _i11.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [movie]),
              returnValue: _i8.Future<_i2.Either<_i9.Failure, String>>.value(
                  _FakeEither_0<_i9.Failure, String>(
                      this, Invocation.method(#removeWatchlist, [movie]))))
          as _i8.Future<_i2.Either<_i9.Failure, String>>);
  @override
  _i8.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: _i8.Future<bool>.value(false)) as _i8.Future<bool>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
              returnValue:
                  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
                      _FakeEither_0<_i9.Failure, List<_i10.Movie>>(
                          this, Invocation.method(#getWatchlistMovies, []))))
          as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i12.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i13.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingMovies, []),
              returnValue:
                  _i8.Future<List<_i13.MovieModel>>.value(<_i13.MovieModel>[]))
          as _i8.Future<List<_i13.MovieModel>>);
  @override
  _i8.Future<List<_i13.MovieModel>> getPopularMovies() =>
      (super.noSuchMethod(Invocation.method(#getPopularMovies, []),
              returnValue:
                  _i8.Future<List<_i13.MovieModel>>.value(<_i13.MovieModel>[]))
          as _i8.Future<List<_i13.MovieModel>>);
  @override
  _i8.Future<List<_i13.MovieModel>> getTopRatedMovies() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedMovies, []),
              returnValue:
                  _i8.Future<List<_i13.MovieModel>>.value(<_i13.MovieModel>[]))
          as _i8.Future<List<_i13.MovieModel>>);
  @override
  _i8.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
              returnValue: _i8.Future<_i3.MovieDetailResponse>.value(
                  _FakeMovieDetailResponse_1(
                      this, Invocation.method(#getMovieDetail, [id]))))
          as _i8.Future<_i3.MovieDetailResponse>);
  @override
  _i8.Future<List<_i13.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
              returnValue:
                  _i8.Future<List<_i13.MovieModel>>.value(<_i13.MovieModel>[]))
          as _i8.Future<List<_i13.MovieModel>>);
  @override
  _i8.Future<List<_i13.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [query]),
              returnValue:
                  _i8.Future<List<_i13.MovieModel>>.value(<_i13.MovieModel>[]))
          as _i8.Future<List<_i13.MovieModel>>);
}

/// A class which mocks [WatchlistLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistLocalDataSource extends _i1.Mock
    implements _i14.WatchlistLocalDataSource {
  MockWatchlistLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String> insertWatchlist(_i15.WatchlistTable? watchlist) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [watchlist]),
          returnValue: _i8.Future<String>.value('')) as _i8.Future<String>);
  @override
  _i8.Future<String> removeWatchlist(_i15.WatchlistTable? watchlist) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [watchlist]),
          returnValue: _i8.Future<String>.value('')) as _i8.Future<String>);
  @override
  _i8.Future<_i15.WatchlistTable?> getWatchlistById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getWatchlistById, [id]),
              returnValue: _i8.Future<_i15.WatchlistTable?>.value())
          as _i8.Future<_i15.WatchlistTable?>);
  @override
  _i8.Future<List<_i15.WatchlistTable>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
              returnValue: _i8.Future<List<_i15.WatchlistTable>>.value(
                  <_i15.WatchlistTable>[]))
          as _i8.Future<List<_i15.WatchlistTable>>);
}

/// A class which mocks [TVSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesRepository extends _i1.Mock
    implements _i16.TVSeriesRepository {
  MockTVSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i17.TVSeries>>>
      getOnTheAirTVSeries() => (super.noSuchMethod(
          Invocation.method(#getOnTheAirTVSeries, []),
          returnValue:
              _i8.Future<_i2.Either<_i9.Failure, List<_i17.TVSeries>>>.value(
                  _FakeEither_0<_i9.Failure, List<_i17.TVSeries>>(this,
                      Invocation.method(#getOnTheAirTVSeries, [])))) as _i8
          .Future<_i2.Either<_i9.Failure, List<_i17.TVSeries>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i17.TVSeries>>>
      getPopularTVSeries() => (super.noSuchMethod(
          Invocation.method(#getPopularTVSeries, []),
          returnValue:
              _i8.Future<_i2.Either<_i9.Failure, List<_i17.TVSeries>>>.value(
                  _FakeEither_0<_i9.Failure, List<_i17.TVSeries>>(
                      this, Invocation.method(#getPopularTVSeries, [])))) as _i8
          .Future<_i2.Either<_i9.Failure, List<_i17.TVSeries>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i17.TVSeries>>>
      getTopRatedTVSeries() => (super.noSuchMethod(
          Invocation.method(#getTopRatedTVSeries, []),
          returnValue:
              _i8.Future<_i2.Either<_i9.Failure, List<_i17.TVSeries>>>.value(
                  _FakeEither_0<_i9.Failure, List<_i17.TVSeries>>(this,
                      Invocation.method(#getTopRatedTVSeries, [])))) as _i8
          .Future<_i2.Either<_i9.Failure, List<_i17.TVSeries>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, _i18.TVSeriesDetail>> getDetailTVSeries(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getDetailTVSeries, [id]),
          returnValue:
              _i8.Future<_i2.Either<_i9.Failure, _i18.TVSeriesDetail>>.value(
                  _FakeEither_0<_i9.Failure, _i18.TVSeriesDetail>(this,
                      Invocation.method(#getDetailTVSeries, [id])))) as _i8
          .Future<_i2.Either<_i9.Failure, _i18.TVSeriesDetail>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i17.TVSeries>>>
      getRecommendationTVSeries(int? id) => (super.noSuchMethod(
              Invocation.method(#getRecommendationTVSeries, [id]),
              returnValue:
                  _i8.Future<_i2.Either<_i9.Failure, List<_i17.TVSeries>>>.value(
                      _FakeEither_0<_i9.Failure, List<_i17.TVSeries>>(this,
                          Invocation.method(#getRecommendationTVSeries, [id]))))
          as _i8.Future<_i2.Either<_i9.Failure, List<_i17.TVSeries>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, _i19.TVSeriesSeasonDetail>>
      getSeasonDetailTVSeries(int? id, int? season) => (super.noSuchMethod(
              Invocation.method(#getSeasonDetailTVSeries, [id, season]),
              returnValue:
                  _i8.Future<_i2.Either<_i9.Failure, _i19.TVSeriesSeasonDetail>>.value(
                      _FakeEither_0<_i9.Failure, _i19.TVSeriesSeasonDetail>(
                          this,
                          Invocation.method(#getSeasonDetailTVSeries, [id, season]))))
          as _i8.Future<_i2.Either<_i9.Failure, _i19.TVSeriesSeasonDetail>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i17.TVSeries>>> searchTVSeries(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTVSeries, [query]),
          returnValue:
              _i8.Future<_i2.Either<_i9.Failure, List<_i17.TVSeries>>>.value(
                  _FakeEither_0<_i9.Failure, List<_i17.TVSeries>>(this,
                      Invocation.method(#searchTVSeries, [query])))) as _i8
          .Future<_i2.Either<_i9.Failure, List<_i17.TVSeries>>>);
}

/// A class which mocks [TVSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesRemoteDataSource extends _i1.Mock
    implements _i20.TVSeriesRemoteDataSource {
  MockTVSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i21.TVSeriesModel>> getOnTheAirTVSeries() =>
      (super.noSuchMethod(Invocation.method(#getOnTheAirTVSeries, []),
          returnValue: _i8.Future<List<_i21.TVSeriesModel>>.value(
              <_i21.TVSeriesModel>[])) as _i8.Future<List<_i21.TVSeriesModel>>);
  @override
  _i8.Future<List<_i21.TVSeriesModel>> getPopularTVSeries() =>
      (super.noSuchMethod(Invocation.method(#getPopularTVSeries, []),
          returnValue: _i8.Future<List<_i21.TVSeriesModel>>.value(
              <_i21.TVSeriesModel>[])) as _i8.Future<List<_i21.TVSeriesModel>>);
  @override
  _i8.Future<List<_i21.TVSeriesModel>> getTopRatedTVSeries() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTVSeries, []),
          returnValue: _i8.Future<List<_i21.TVSeriesModel>>.value(
              <_i21.TVSeriesModel>[])) as _i8.Future<List<_i21.TVSeriesModel>>);
  @override
  _i8.Future<_i4.TVSeriesDetailResponseModel> getDetailTVSeries(int? id) =>
      (super.noSuchMethod(Invocation.method(#getDetailTVSeries, [id]),
              returnValue: _i8.Future<_i4.TVSeriesDetailResponseModel>.value(
                  _FakeTVSeriesDetailResponseModel_2(
                      this, Invocation.method(#getDetailTVSeries, [id]))))
          as _i8.Future<_i4.TVSeriesDetailResponseModel>);
  @override
  _i8.Future<List<_i21.TVSeriesModel>> searchTVSeries(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTVSeries, [query]),
          returnValue: _i8.Future<List<_i21.TVSeriesModel>>.value(
              <_i21.TVSeriesModel>[])) as _i8.Future<List<_i21.TVSeriesModel>>);
  @override
  _i8.Future<_i5.TVSeriesSeasonDetailModel> getSeasonDetailTVSeries(
          int? id, int? season) =>
      (super.noSuchMethod(
              Invocation.method(#getSeasonDetailTVSeries, [id, season]),
              returnValue: _i8.Future<_i5.TVSeriesSeasonDetailModel>.value(
                  _FakeTVSeriesSeasonDetailModel_3(
                      this,
                      Invocation.method(
                          #getSeasonDetailTVSeries, [id, season]))))
          as _i8.Future<_i5.TVSeriesSeasonDetailModel>);
  @override
  _i8.Future<List<_i21.TVSeriesModel>> getRecommendationTVSeries(int? id) =>
      (super.noSuchMethod(Invocation.method(#getRecommendationTVSeries, [id]),
          returnValue: _i8.Future<List<_i21.TVSeriesModel>>.value(
              <_i21.TVSeriesModel>[])) as _i8.Future<List<_i21.TVSeriesModel>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i22.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i23.Database?> get database =>
      (super.noSuchMethod(Invocation.getter(#database),
              returnValue: _i8.Future<_i23.Database?>.value())
          as _i8.Future<_i23.Database?>);
  @override
  _i8.Future<int> insertWatchlist(_i15.WatchlistTable? watchlist) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [watchlist]),
          returnValue: _i8.Future<int>.value(0)) as _i8.Future<int>);
  @override
  _i8.Future<int> removeWatchlist(_i15.WatchlistTable? watchlist) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [watchlist]),
          returnValue: _i8.Future<int>.value(0)) as _i8.Future<int>);
  @override
  _i8.Future<Map<String, dynamic>?> getWatchlistById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getWatchlistById, [id]),
              returnValue: _i8.Future<Map<String, dynamic>?>.value())
          as _i8.Future<Map<String, dynamic>?>);
  @override
  _i8.Future<List<Map<String, dynamic>>> getWatchlist() => (super.noSuchMethod(
      Invocation.method(#getWatchlist, []),
      returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
          <Map<String, dynamic>>[])) as _i8.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i6.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
                  this, Invocation.method(#head, [url], {#headers: headers}))))
          as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
                  this, Invocation.method(#get, [url], {#headers: headers}))))
          as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i24.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#post, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
                  this,
                  Invocation.method(#post, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i24.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#put, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
                  this,
                  Invocation.method(#put, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i24.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#patch, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
                  this,
                  Invocation.method(#patch, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i24.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#delete, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
                  this,
                  Invocation.method(#delete, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i8.Future<_i6.Response>);
  @override
  _i8.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: _i8.Future<String>.value('')) as _i8.Future<String>);
  @override
  _i8.Future<_i25.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: _i8.Future<_i25.Uint8List>.value(_i25.Uint8List(0)))
          as _i8.Future<_i25.Uint8List>);
  @override
  _i8.Future<_i6.StreamedResponse> send(_i6.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue: _i8.Future<_i6.StreamedResponse>.value(
                  _FakeStreamedResponse_5(
                      this, Invocation.method(#send, [request]))))
          as _i8.Future<_i6.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}
